# Generated by Django 4.2.5 on 2023-09-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0002_problem_actions_taken_problem_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
