# Generated by Django 4.2.5 on 2023-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10),
        ),
    ]
