# Generated by Django 4.2.5 on 2023-09-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0008_problem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='status',
        ),
    ]
