# Generated by Django 4.2.5 on 2023-09-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0010_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='actions',
            field=models.TextField(blank=True),
        ),
    ]
