# Generated by Django 4.2.5 on 2023-09-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_app', '0013_baduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadUser',
        ),
    ]
